### ISSUE TITLE
Cache hit gives 200 instead of 304 when behind Nginx

### ISSUE THREAD

**Issue by jackdesert** [rtomayko/rack-cache#111]
How do I get rack-cache to return a 304 when behind nginx?

Here is a sinatra example with etag that works functionally, but when used behind nginx it returns a status code of 200 when I expected a 304. When accessed directly (without nginx) it returns a 304 most of the time, as expected.

    get '/' do
      cache_control :public
      the_etag = "#{Message.last.try(:id)}"
      etag the_etag
      "cache: #{Time.now}, etag: #{the_etag}"
    end

Here is the Sinatra log:

    cache: [GET /] stale, valid, store
    127.0.0.1 - - [12/Apr/2015:03:52:55 -0400] "GET / HTTP/1.0" 200 91093 0.0039

By halting at a breakpoint during the request both with_nginx and without_nxinx, those parts of env that show up with ALL_CAPS keys were captured. Showing only the diff:

    $ diff with_nginx without_nginx
    3c3
    < "rack.input"=>#<StringIO:0x007f5ae98891b8>,
    ---
    > "rack.input"=>#<StringIO:0x007f5aeb287ec0>,
    12,16c12,15
    < "HTTP_VERSION"=>"HTTP/1.0",
    < "HTTP_HOST"=>"example.com",
    < "HTTP_CONNECTION"=>"close",
    ---
    > "HTTP_VERSION"=>"HTTP/1.1",
    > "HTTP_HOST"=>"example.com:8852",
    22c21
    ---
    > "HTTP_CONNECTION"=>"keep-alive",
    24c23
    < "SERVER_PORT"=>"80",
    ---
    > "SERVER_PORT"=>"8852",
    28c27
    < "REMOTE_ADDR"=>"127.0.0.1",
    ---
    > "REMOTE_ADDR"=>"74.59.192.69",

**Comment by jackdesert** [comment]
Update: Discovered that caching had been disabled in my browser.

Now that cache is enabled, the rack-cache sinatra example returns a 304 as expected. 

However, the etag example I that I pasted in returns a 200 sometimes, and returns a 304 other times. In both cases, it successfully bypasses the heavy database call that are meant to be cached. So like I said, it is being cached, but for some reason it comes back as 200 instead of 304 (but intermittently)

I even tried setting max_age to 0, and that make a difference locally but not in production. (Production is running behind nginx---I don't know if that makes a difference)

**Comment by jackdesert** [comment]
Update: Have verified that in production if I hit the sinatra app directly by using its port number in the url, the server returns a 304 as expected. But if nginx is allowed to proxy the request, the request comes back as 200. 

Is there something special that nginx needs to tell rack-cache (or vice versa) to get a 304 with a nginx / sinatra / rack-cache system?

**Comment by jackdesert** [comment]
Update: tailed the sinatra logs and verified that when behind nginx, sinatra delivers a 200 (even when the caching benefit is noticeable).

This leads me to believe that nginx is not passing something through to sinatra.

**Comment by jackdesert** [comment]
Here is the sinatra log:
    cache: [GET /] stale, valid, store
    127.0.0.1 - - [12/Apr/2015:03:52:55 -0400] "GET / HTTP/1.0" 200 91093 0.0039

**Comment by jackdesert** [comment]
By halting at a breakpoint during the request both with_nginx and without_nxinx, these parts of `env` were captured. Showing only the diff:

    $ diff with_nginx without_nginx
    3c3
    < "rack.input"=>#<StringIO:0x007f5ae98891b8>,
    ---
    > "rack.input"=>#<StringIO:0x007f5aeb287ec0>,
    12,16c12,15
    < "REQUEST_URI"=>"/",
    < "HTTP_VERSION"=>"HTTP/1.0",
    < "HTTP_HOST"=>"example.com",
    < "HTTP_CONNECTION"=>"close",
    ---
    > "REQUEST_URI"=>"/",
    > "HTTP_VERSION"=>"HTTP/1.1",
    > "HTTP_HOST"=>"example.com:8852",
    22c21
    < "HTTP_CACHE_CONTROL"=>"max-age=0",
    ---
    > "HTTP_CONNECTION"=>"keep-alive",
    24c23
    < "SERVER_PORT"=>"80",
    ---
    > "SERVER_PORT"=>"8852",
    28c27
    < "REMOTE_ADDR"=>"127.0.0.1",
    ---
    > "REMOTE_ADDR"=>"74.59.192.69",

**Comment by jackdesert** [comment]
Found the answer here: http://forum.nginx.org/read.php?2,242807,242809#msg-242809
The etag was being stripped by nginx because gzip compression was enabled. 
Had to disable gzip compression in nginx to get it to work.

**Comment by rtomayko** [comment]
Awesome. Thanks so much for the detailed write up @jackdesert. It'll live on in google for the next person :)

**Comment by jackdesert** [comment]
Since I'm kind of attached to leaving gzip compression enabled in nginx, ultimately I patched nginx with this: 
http://forum.nginx.org/read.php?2,240120,243846#msg-243846
Which makes it so that weak etags are not stripped in nginx, even when gzip is enabled.
