### ISSUE TITLE
Cache-Control: public in response when Cache-Control: no-cache in request

### ISSUE THREAD

**Issue by ip2k** [rtomayko/rack-cache#114]
When I 
```
use Rack::Cache,
  :verbose          => true,
  :allow_reload     => true,
  :allow_revalidate => true

before do
  expires 300, :public
end
```

in my Sinatra app and send it a request like:

`curl -vvv 'http://127.0.0.1:4567/foo'  -H 'Cache-Control: no-cache' -o /dev/null`

it responds with `Cache-Control: public, max-age=300` and `X-Rack-Cache: reload, store`.

I've hacked around this by doing:

```
before do
  expires 300, :public unless request.env['HTTP_CACHE_CONTROL'] == 'no-cache'
end
```

which responds with no `Cache-Control` header, and `X-Rack-Cache: reload`, which is what I would think should happen without my hack. It might be also nice to have an option to NOT store responses when a request specifies `Cache-Control: no-cache` 

Thanks!

**Comment by mezis** [comment]
@ip2k: I believe this behaviour is actually correct. `Cache-Control: no-cache` in the request asks the server to provide an _uncached_ response, which it does (as mentioned by `X-Rack-Cache: reload`).
The `Cache-Control: public` in the response specifies that the client _may_ cache the response.

In other words, the fact you asked for your data not to come from the cache has no bearing on whether the response will be cached, or can be cached.

Unless I'm missing something or misreading RFC2616?

**Comment by grosser** [comment]
sounds good to me ... thx for digging into the RFCs ... I know it's dirty work :D
