### ISSUE TITLE
Please add new maintainers

### ISSUE THREAD

**Issue by brauliobo** [rtomayko/rack-cache#115]
There is a lot of issues and PRs to this project but not enough feedback. New maintainers could help to make the project go forward.

**Comment by fabn** [comment]
@rtomayko more than two years with no commit on this repository, could you tell us if this project is dead or there is some hope to have some new maintainers. Thanks.

**Comment by Fuffi** [comment]
@rtomayko +1 for the request, please Lazarus stand up and walk!

**Comment by xentek** [comment]
Fork and Release that to rubygems.

**Comment by rtomayko** [comment]
Hey all, @grosser has volunteered to help maintain rack-cache and I've added him as a collab on this repository and to rubygems.org. We're going to focus on getting a 1.3 release out with the current set of unreleased changes on master:

https://github.com/rtomayko/rack-cache/compare/1.2...master

Changes in the near term are likely to be limited to bug fixes and getting the development/test environment tidied up.

Apologies for the lack of attention. Hopefully we'll see some movement on a release this week.

**Comment by renatocarvalho** [comment]
:+1:

**Comment by brauliobo** [comment]
nice @rtomayko, thanks!
