### ISSUE TITLE
Shouldn't rack cache ignore http vs https?

### ISSUE THREAD

**Issue by krisdigital** [rtomayko/rack-cache#128]
I am working on a Rails app which uses rack cache to store processed images (with the [dragonfly gem](https://github.com/markevans/dragonfly)). I noticed that changing the protocol to https forces a regeneration of all images, which is bad for performance and bad for the disk space.

I just went through the code shortly, should not https://github.com/rtomayko/rack-cache/blob/master/lib/rack/cache/key.rb normalize the cache key for both protocols?

**Comment by grosser** [comment]
in your case yes, but I think it's dangerous to generalize that, the app might respond differently to http and https requests (redirect / do other things) ... so feel free to patch it on your end or open a PR for an optional ignore_protocol setting.

**Comment by krisdigital** [comment]
Thank you for answering. I thought the code I pointed to that generates the cache key would already do that and wondered why it did not work. I will investigate further and think about what makes more sense..

**Comment by krisdigital** [comment]
I found out that RackCache has an option `:cache_key`which lets you override the Cache-Key Class or provide a block, that generates the Cache Key. So all I needed to do was create a new class and override the generate method.

````
require 'rack/cache/key'

class RackCacheKey < Rack::Cache::Key
  def generate
    parts = super
    parts.gsub!(/^https/, 'http')
  end
end
````

and

````
config.action_dispatch.rack_cache = {
    :metastore => 'file:tmp/cache/rack/meta',
    :entitystore => 'file:tmp/cache/rack/body',
    :cache_key => RackCacheKey
  }
````

I absolutely agree that this should not be the default behaviour and it is easy enough to customize!
