### ISSUE TITLE
Key should take into account more than URI

### ISSUE THREAD

**Issue by jamesarosen** [rtomayko/rack-cache#13]
As far as I can tell, `Rack::Cache::Key` only takes into account protocol, domain, path, and query parameters. Different user-agents might request the same URL and expect to get different results. I see two major factors that `Key` ignores: the `Accepts` header and the `Accepts-Language` header. That is, if a German-speaking user requests the HTML version of a resource and then a Portuguese-speaking person requests the JSON version, the Portuguese person will get the German HTML.

Additionally, it might be important to also take the HTTP verb into account. With only the five basic verbs (HEAD, GET, POST, PUT, and DELETE) there's probably not much of an issue -- `Rack::Cache` should only be caching GETs anyway. Once you try to put WebDAV or CalDAV behind `Rack::Cache`, though, things might get a little hairier.

**Comment by futuretap** [comment]
Should be explained in the Readme.

**Comment by grosser** [comment]
PR welcome!

**Comment by futuretap** [comment]
I would but I've no insight how this actually works. Does Rack::Cache read the Vary header?

**Comment by grosser** [comment]
idk ... git-grep might find it
