### ISSUE TITLE
Changelog is not up to date

### ISSUE THREAD

**Issue by rocknruby** [rtomayko/rack-cache#137]
Missing changelog entry for version `1.6.1`

**Comment by grosser** [comment]
updated

**Comment by grosser** [comment]
Reverts `No longer read responses from cache when we already have them`

**Comment by rocknruby** [comment]
:+1:

**Comment by pelargir** [comment]
Changelog is missing entries for 1.14.0, 1.15.0, and 1.16.0. It's very difficult to determine if we can upgrade safely without any information on what has actually changed between versions.

**Comment by grosser** [comment]
Can you make a PR to fix ?
