### ISSUE TITLE
Is it possible to use rack cache with HTTPS? 

### ISSUE THREAD

**Issue by fearnowrath** [rtomayko/rack-cache#139]
Does Rack Cache Support HTTPS? I have a site built with Roda gem and use Rack Cache for caching. Is it possible to use Rack cache if i add SSL to the site? if so, how and what extra stuff needs to be done?

**Comment by grosser** [comment]
Caching would be done before https encryption, so it should just work.

**Comment by CertifiedWebMaster** [comment]
If this is done before HTTPS Encryption would this not present opportunity for unwanted Cache Deposits making vulnerability ?

**Comment by grosser** [comment]
if someone can poison your cache (via bad crafted request that gets cached), that sure would be a problem :)
... nothin to do with https though, just a general issue
