### ISSUE TITLE
Permission denied @ dir_s_mkdir - /var/cache

### ISSUE THREAD

**Issue by arnoldfungai** [rtomayko/rack-cache#141]
I am trying to setup a basic cache with my static single page app using Heroku with Rack. However, I am obtaining the following error when I rackup the app.
`cache error: Permission denied @ dir_s_mkdir - /var/cache`

**Comment by grosser** [comment]
Don't use a file store cache ... or use it with a directory you have write
access to.

**Comment by arnoldfungai** [comment]
@grosser Thank you for clarifying the error. Now  Resolved

Can web browser caching also be done with Rack-Cache for offline apps using ?

**Comment by grosser** [comment]
nah, rack-cache is a server-side cache

**Comment by arnoldfungai** [comment]
@grosser - Do you have any ideas on how to implement cache manifest on a rack app?

**Comment by grosser** [comment]
send back cache headers ... if you find something nice a small readme section on this would be great :)
can also steal from old faq http://rtomayko.github.io/rack-cache/faq
http://2ndscale.com/rtomayko/2008/things-caches-do and http://rtomayko.github.io/rack-cache/
