### ISSUE TITLE
Move to rack org?

### ISSUE THREAD

**Issue by ioquatix** [rtomayko/rack-cache#165]
Hi, it looks like it could be great to move this repo to the rack for for shared maintainership.

Let me know if that's something you are interested in.

We'd still want you to have ownership over the project, but we'd also like to help move it forward w.r.t. the coming changes with Rack 3.

**Comment by amatriain** [comment]
I hope this proposal is accepted. This project is not really unmaintained, but it deserves more love than it's getting, and it absolutely should be kept in sync with any important changes in Rack.

**Comment by grosser** [comment]
Sounds good!
@rtomayko is the only one who can move it though

**Comment by ioquatix** [comment]
cc @tenderlove

**Comment by dani-sc** [comment]
Any updates on this? Improved maintenance would be nice.

**Comment by ioquatix** [comment]
I emailed both @grosser and @rtomayko but did not receive any reply.

I'm going to suggest we fork this repo to then rack org. If @grosser is on board with this, can you please add myself as an owner of the gem too so we can handle release management? Thanks!

**Comment by grosser** [comment]
need your rubygems email

**Comment by grosser** [comment]
... also there are no issues or PRs here, so doubt this will have much impact 🤷 
but better there then here ...

**Comment by ioquatix** [comment]
@grosser can you DM me on twitter? `@ioquatix`

**Comment by grosser** [comment]
worked via username too :)

**Comment by ioquatix** [comment]
I've just asked other maintainers to let me know if there are any issues with forking this repo to the rack org. If not, I'll do it later this week.

**Comment by ioquatix** [comment]
I've made a temporary "detached" fork https://github.com/ioquatix/rack-cache which I'm going to use for testing, and I can move this to the rack org later. I'll add you as a maintainer.
