### ISSUE TITLE
Rake middleware display "use Module" instead of "use Rack::Cache"

### ISSUE THREAD

**Issue by Etienne-C** [rtomayko/rack-cache#172]
Hello, 

I am trying to use rake cache with memcached (I followed the instructions : https://devcenter.heroku.com/articles/rack-cache-memcached-rails31)

When I run
`rake middleware`

I have this 
`use Module
use Rack::Sendfile
use ActionDispatch::Static
use ActionDispatch::Executor
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Sprockets::Rails::QuietAssets
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use MetaRequest::Middlewares::Headers
use ActionDispatch::DebugExceptions
use BetterErrors::Middleware
use ActionDispatch::RemoteIp
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Warden::Manager
use Rack::Deflater
use Rack::Attack
use ScoutApm::Middleware
use ScoutApm::Instant::Middleware
use MetaRequest::Middlewares::MetaRequestHandler
use MetaRequest::Middlewares::AppRequestHandler
use OmniAuth::Strategies::LinkedIn
run MYAPP::Application.routes
`

I used in my application.rb "config.middleware.insert_before Rack::Sendfile, Rack::Cache" to check that "use module" it was really corresponding to Rack::cache in the first position in the list. 

I am using Ruby 2.3.1 and Rails 5.0.0.1

About the configuration I added thi in my production.rb
` client = Dalli::Client.new((ENV["MEMCACHIER_SERVERS"] || "").split(","),
                           :username => ENV["MEMCACHIER_USERNAME"],
                           :password => ENV["MEMCACHIER_PASSWORD"],
                           :failover => true,
                           :socket_timeout => 1.5,
                           :socket_failure_delay => 0.2,
                           :value_max_bytes => 10485760)
  config.action_dispatch.rack_cache = {
    :metastore    => client,
    :entitystore  => client
  }
  config.public_file_server.headers = { 'Cache-Control' => 'public, max-age=2592000' }`

A the end Rack::Cache is not working, when I check an asset there is no "X-Rack-Cache: fresh" in the return command.
Any idea ? 

Thx

**Comment by grosser** [comment]
best follow newer instructions, rails 3.1 / 5 is long dead
if you have a failing example app on a recent version of ruby/rails I can help debug
