### ISSUE TITLE
No git tag since release 1.13.0

### ISSUE THREAD

**Issue by Segaja** [rtomayko/rack-cache#176]
Hello,

I see new releases up to version 1.17.0 on https://rubygems.org/gems/rack-cache but the last git tag i see on https://github.com/rtomayko/rack-cache/tags is 1.13.0.

Arch Linux is packaging this gem based on github tags and not from rubygems, so right now we can't update this as there are git tags for the latest versions

**Comment by grosser** [comment]
plz get it from https://github.com/rack/rack-cache
